import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '@supercampus/supabase';
import { useTheme } from '@supercampus/shared';
import { useSidebar } from '../navigation/NavigationProvider';

function Header(): React.ReactElement { const { theme,toggleTheme }=useTheme();const{user,signOut}=useAuth();return <header className="sc-topbar"><strong className="sc-topbar-logo">SUPERCAMPUS</strong><div className="sc-topbar-actions"><button type="button" className="sc-icon-btn" aria-label="Search" title="Search coming soon">⌕</button><button type="button" className="sc-icon-btn" aria-label="Notifications" title="Notifications coming soon">🔔</button><button type="button" className="sc-icon-btn" aria-label="Toggle theme" onClick={toggleTheme}>{theme==='dark'?'☀':'◐'}</button><button type="button" className="sc-icon-btn" aria-label="Sign out" onClick={()=>void signOut()}>{user?.email?.slice(0,1).toUpperCase()||'U'}</button></div></header>}
function Sidebar({collapsed,onToggle}:{collapsed:boolean;onToggle:()=>void}):React.ReactElement{const items=useSidebar();const location=useLocation();const[more,setMore]=useState(false);const primary=items.slice(0,5),remaining=items.slice(5);const item=(entry:typeof items[number])=>{const active=location.pathname===entry.route||location.pathname.startsWith(`${entry.route}/`);return <Link key={entry.id} to={entry.route} title={entry.title} className={`sc-nav-item${active?' active':''}`} aria-current={active?'page':undefined} onClick={()=>setMore(false)}><span className="sc-nav-icon" aria-hidden="true">{entry.icon}</span><span className="sc-nav-label">{entry.title}</span></Link>};return <><nav className={`sc-bottom-nav sc-desktop-sidebar${collapsed?' is-collapsed':''}`} aria-label="Application navigation"><button type="button" className="sc-sidebar-toggle" onClick={onToggle} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'}>☰</button><div className="sc-desktop-items">{items.map(item)}</div><div className="sc-mobile-items">{primary.map(item)}{remaining.length?<button type="button" className="sc-nav-item" onClick={()=>setMore(true)} aria-expanded={more} aria-controls="more-navigation"><span className="sc-nav-icon">•••</span><span>More</span></button>:null}</div></nav>{more?<div className="sc-more-backdrop" role="presentation" onClick={()=>setMore(false)}><aside id="more-navigation" className="sc-more-drawer" role="dialog" aria-modal="true" aria-label="More navigation" onClick={(e)=>e.stopPropagation()}><button type="button" className="sc-icon-btn" onClick={()=>setMore(false)} aria-label="Close more navigation">×</button>{remaining.map(item)}</aside></div>:null}</>}
export function AppLayout({children}:{children:React.ReactNode}):React.ReactElement{const[collapsed,setCollapsed]=useState(false);console.log('AppLayout rendered');return <div className={`sc-app-shell${collapsed?' sc-shell-collapsed':''}`}><Header/><Sidebar collapsed={collapsed} onToggle={()=>setCollapsed(v=>!v)}/><main className="sc-app-main" tabIndex={-1}>{children}</main></div>}
